name: Bug Report
description: File a bug report
title: "[BUG] "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Please describe the bug.
      placeholder: A clear and concise description of what the bug is.
      render: markdown
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What should have happened? (optional)
      description: Please describe the expected behaviour.
      placeholder: A clear and concise description of what you expected to happen.
      render: markdown
  - type: textarea
    id: reproduce
    attributes:
      label: How to reproduce the bug?
      description: Please describe the expected behaviour.
      placeholder: |
        Steps to reproduce the behavior:
          1. Go to '...'
          2. Click on '....'
          3. Scroll down to '....'
          4. See error
      render: markdown
    validations:
      required: true
  - type: input
    id: plugin-version
    attributes:
      label: Plugin version
      description: What version of the plugin are you running?
      placeholder: e.g. v2.2.5
    validations:
      required: true
  - type: input
    id: python-version
    attributes:
      label: Python version
      description: What version of Python are you running the plugin on?
      placeholder: "e.g. 3.9"
    validations:
      required: true
  - type: textarea
    id: other-env
    attributes:
      label: Additional environment information (optional)
      description: Additional information about your environment, e.g. OS version.
      placeholder: "- **OS**: Ubuntu 22.04"
      render: markdown
  - type: textarea
    id: context
    attributes:
      label: Additional context (optional)
      description: Add any other context about the problem here.
      render: markdown
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output (optional)
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
