name: test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.6.7"
      - run: pip install -r requirements.txt
      - run: python -m unittest

  test_higher:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.11.0"
      - run: pip install -r requirements.txt
      - run: python -m unittest
